curl -X POST http://localhost:3000/addClients \
     -H "Content-Type: application/json" \
     -d '{"Prenom": "John", "nom": "Doe", "Telephone": "41421121", "email": "asndy@sam.com", "adresse": "123 Main St"}'

curl http://localhost:3000/allClients


curl -X DELETE http://localhost:3000/deleteClient/1


//=================================== TESTS PRETS ===================================

curl -X POST http://localhost:3000/addPrets \
     -H "Content-Type: application/json" \
     -d '{"client_id": 1, "montantPret": 20000, "dureeMois": 24, "tauxInteret": 5.5}'

curl http://localhost:3000/allPrets

curl -X DELETE http://localhost:3000/deletePret/1

curl -X PUT http://localhost:3000/updatePret/1 \
     -H "Content-Type: application/json" \
     -d '{"montantPret": 25000, "dureeMois": 36}'


curl -X POST http://localhost:3000/addClients `
     -H "Content-Type: application/json" `
     -d '{"prenom": "John", "nom": "Doe", "telephone": "41421121", "email": "asndy@sam.com", "adresse": "123 Main St"}'


### Migrer les dates des prêts existants
POST http://localhost:3000/migrerDatesPretsExistants
Content-Type: application/json

{}